project Expolore-with-me – working with branch stat-svc ver 1.0
EllaStani/java-explore-with-me pull request #3
Opened 2023-04-12 12:53 UTC by EllaStani

2023-04-13 19:40 UTC, alexache requested changes

2023-04-13 19:40 UTC, alexache commented on stats/stats-server/src/main/java/ru/practicum/hit/HitController.java
> +    public HitInDto saveNewHit(@RequestBody HitInDto hitDto) {
Может еще стоит валидировать входные данные?

2023-04-13 19:40 UTC, alexache commented on stats/stats-client/src/main/java/hit/HitClient.java
> +                "uri", uri,
Мне кажется, что это не самый правильный способ передачи массива от клиента к рест серверу. Проверялась ли работа данного клиента?

2023-04-13 19:40 UTC, alexache commented on stats/stats-client/src/main/java/hit/HitClient.java
> +        return get("/stats?start={start}&end={end}&uri={{uri}}&unique={unique}", parameters);
Как работать с Object после этого? Как посмотреть количество просмотров?

2023-04-13 19:40 UTC, alexache commented on stats/stats-server/src/main/java/ru/practicum/hit/HitServiceImpl.java
> +    private Hit mapToHit(HitInDto hitDto) {
Можно вынести в отдельный маппер конвертации

2023-04-15 12:48 UTC, EllaStani commented on stats/stats-server/src/main/java/ru/practicum/hit/HitController.java
> +    public HitInDto saveNewHit(@RequestBody HitInDto hitDto) {
валидацию добавила

2023-04-15 12:49 UTC, EllaStani commented on stats/stats-client/src/main/java/hit/HitClient.java
> +                "uri", uri,
Ошибку исправила, работу клиента проверила, работает

2023-04-15 12:49 UTC, EllaStani commented on stats/stats-client/src/main/java/hit/HitClient.java
> +        return get("/stats?start={start}&end={end}&uri={{uri}}&unique={unique}", parameters);
Добавила маппер

2023-04-15 22:53 UTC, alexache approved these changes

2023-04-18 07:03 UTC, merged