project Expolore-with-me – working with branch main_svc ver 1.0
EllaStani/java-explore-with-me pull request #4
Opened 2023-04-30 20:39 UTC by EllaStani

2023-05-06 21:35 UTC, alexache requested changes

2023-05-06 21:35 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/compilation/CompilationServiceImpl.java
> +                .map(id -> eventRepository.findById(id).get())
Это запрос к базе в цикле. такого не должно быть, нужен один запрос по списку

2023-05-06 21:35 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/controller/PublicEventController.java
> +    private final HttpServletRequest request;
Почему это не просто аргумент метода контроллера?

2023-05-06 21:35 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/Request.java
> +    public String toString() {
Зачем есть и аннотация @ToString на классе?

2023-05-06 21:35 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/RequestServiceImpl.java
> +        List<Request> requests = requestRepository.findRequestByEventIdAndRequesterId(eventId, userId);
(опционально) это можно решать и exists*() методами

2023-05-06 21:35 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/RequestServiceImpl.java
> +                requestRepository.save(r);
Много как-то запросов на save

2023-05-06 21:35 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/RequestServiceImpl.java
> +                rejRequests.remove(req);
Можно делать немного оптимальнее - сложить в confRequests сразу нужное количество заявок, которые можно подтвердить. а в rejRequests все остальные

2023-05-06 21:35 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/RequestServiceImpl.java
> +                requestRepository.save(req);
Сохранение в цикле не очень хорошо. лучше единожды вызвать saveAll

2023-05-06 21:35 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/dto/RequestUpdateStatusOutDto.java
> +    List<ParticipationRequestDto> confirmedRequests;
Модификаторы доступа полей?

2023-05-06 21:35 UTC, alexache commented on stats/stats-client/src/main/java/hit/HitClient.java
> +    DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Модификатор доступа

2023-05-06 21:35 UTC, alexache commented on stats/stats-client/src/main/java/hit/HitClient.java
> +                uriBuilder.append("&uris=").append(uri);
Что-то усложненное, почему весь список URI не указать одним списком?

2023-05-06 21:35 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/EventServiceImpl.java
> +            for (int i = 0; i < users.length; i++) {
Это просто перекладывание из массива в список? Почему не просто List.of? И для чего вообще массивы вместо списков на вход?

2023-05-06 21:35 UTC, alexache commented on stats/stats-client/src/main/java/hit/HitClient.java
> +    public void saveNewHit(HitInDto hitInDto) {
Почему этот и следующий метод разделены?

2023-05-06 21:35 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/EventServiceImpl.java
> +            checkingExistCategory(catId[i]);
Запросы к базе в цикле - это плохо

2023-05-06 21:35 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/EventServiceImpl.java
> +    private EventFullDto makeEventFullDtoWithViews(EventFullDto eventFullDto, int count) {
Какие-то пустоватые методы из 1-2 строк

2023-05-07 14:56 UTC, EllaStani commented on ewm-service/src/main/java/ru/practicum/event/controller/PublicEventController.java
> +    private final HttpServletRequest request;
Исправила

2023-05-07 14:57 UTC, EllaStani commented on ewm-service/src/main/java/ru/practicum/event/EventServiceImpl.java
> +            for (int i = 0; i < users.length; i++) {
Исправила

2023-05-07 14:57 UTC, EllaStani commented on ewm-service/src/main/java/ru/practicum/event/EventServiceImpl.java
> +            checkingExistCategory(catId[i]);
Исправила

2023-05-07 14:58 UTC, EllaStani commented on ewm-service/src/main/java/ru/practicum/event/EventServiceImpl.java
> +    private EventFullDto makeEventFullDtoWithViews(EventFullDto eventFullDto, int count) {
Изменила

2023-05-07 15:11 UTC, EllaStani commented on ewm-service/pom.xml
> +            <groupId>org.apache.httpcomponents</groupId>
Удалила

2023-05-07 15:11 UTC, EllaStani commented on ewm-service/src/main/java/ru/practicum/category/CategoryServiceImpl.java
> +        categoryRepository.deleteById(catId);
Добавила проверку

2023-05-07 15:13 UTC, EllaStani commented on ewm-service/src/main/java/ru/practicum/category/controller/AdminCategoryController.java
> +    public CategoryDto saveNewCategory(@Validated @RequestBody CategoryNewDto categoryNewDto) {
Исправила везде

2023-05-07 15:17 UTC, EllaStani commented on ewm-service/src/main/java/ru/practicum/compilation/CompilationServiceImpl.java
> +                .map(id -> eventRepository.findById(id).get())
Да, бред у меня, переделала

2023-05-07 15:36 UTC, EllaStani commented on stats/stats-client/src/main/java/hit/HitClient.java
> +    public void saveNewHit(HitInDto hitInDto) {
Исправила

2023-05-07 16:47 UTC, EllaStani commented on stats/stats-client/src/main/java/hit/HitClient.java
> +                uriBuilder.append("&uris=").append(uri);
Александр! Перепробовала разные варианты, только так получается. Полдня билась, в других случаях передается список списков и т.п.

2023-05-08 05:16 UTC, alexache approved these changes

2023-05-08 05:16 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/category/CategoryServiceImpl.java
> +        if (eventRepository.findEventByCategoryId(catId).size() == 0) {
Когда сами объекты не нужны, лучше использовать петоды репо как countEventBy existsEventBy

2023-05-08 05:16 UTC, alexache commented on stats/stats-client/src/main/java/hit/HitClient.java
> +    DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Этот комментарий остался нерешенным

2023-05-08 05:16 UTC, alexache commented on stats/stats-client/src/main/java/hit/HitClient.java
> +                uriBuilder.append("&uris=").append(uri);
Не критичный комментарий

2023-05-09 09:44 UTC, merged